Index bootsrapped
Guillaumejfrt/ticktock_app pull request #44
Opened 2017-05-16 18:27 UTC by ArianePhelizot

![capture d ecran 2017-05-16 a 20 21 56](https://cloud.githubusercontent.com/assets/22742423/26121708/7303730a-3a75-11e7-869f-fa6eb0a29574.png)

Hello à vous,

Voici l'index
Il me semble avoir respecté scrupuleusement le modèle thumbnail de Bootstrap mais le résultat n'est pas encore au top
Quelque chose doit bloquer. Vous avez le même type de problème?
Je veux bien que vous regardiez si ça vient de mon code
Si ok pour vous, on merge
...Je vais manger
Je passe après à la nav, après avoir fait une pul request pour repartir du master.
Je repasserai après un peu temps pour investiguer ce qui override bootstrap + ce qui gêne sur le footer si je suis encore alive
Merci pour vos retours!

2017-05-16 21:14 UTC, ArianePhelizot commented
![capture d ecran 2017-05-16 a 23 11 48](https://cloud.githubusercontent.com/assets/22742423/26128582/2a626b98-3a8d-11e7-9a11-ae4e310cb697.png)

Beaucoup, beaucoup mieux! Merci Guiguijo!
Il faudra sûrement somewhere, à voir où, fixer avec une classe la hauteur des cartes pour éviter les décalages avec/sans description

2017-05-17 07:45 UTC, Guillaumejfrt requested changes
@ArianePhelizot tu peux créer un composant thumbnail en lui donnant une class `.thumbnail-height` qui contient la height souhaitée

2017-05-17 07:45 UTC, Guillaumejfrt commented on app/views/watches/index.html.erb
> +      <div class="col-sm-6 col-md-4">
@ArianePhelizot teste ceci: `<div class="col-sm-6 col-md-3">`
A mon avis tes photos sont grandes par rapport aux colonnes, donc bootstrap essaye d'en afficher 4 alors qu'il n'a la place que pour 3.

2017-05-17 12:34 UTC, ArianePhelizot commented
Done!
![capture d ecran 2017-05-17 a 14 03 25](https://cloud.githubusercontent.com/assets/22742423/26153976/fe61663a-3b0d-11e7-8221-cc5656962b47.png)

2017-05-17 12:35 UTC, ArianePhelizot commented
A vos feedbacks et merge!
Thanks

2017-05-17 12:42 UTC, Guillaumejfrt approved these changes

2017-05-17 12:43 UTC, merged